app = "grab-shop"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 3000
  protocol      = "tcp"

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls","http"]

  [services.concurrency]
    type       = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.tcp_checks]]
    grace_period  = "5s"
    interval      = "15s"
    timeout       = "2s"
    restart_limit = 0
